vaadin:
  launch-browser: 'true'
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,co.lecompany.app
  url-mapping: /web/*

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:password}

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  sql:
    init:
      mode: always
  mustache:
    check-template-location: 'false'
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
